import { KEPCUP_RESULT_BEGIN, KEPCUP_RESULT_END } from './constants.js';
import type { SandboxViolation } from '../types.js';

/**
 * Wire protocol between the core (Windows/macOS/Linux host) and the
 * in-VM/in-distro shim `/opt/kepcup/bin/kepcup-sandbox` (built from
 * apps/desktop/scripts/build-wsl-rootfs/kepcup-sandbox.mjs into every sandbox
 * image: the WSL rootfs, the Podman image and the Lima VM).
 *
 * Request: JSON on stdin. The shim wraps the command with srt inside the
 * sandbox VM (the same library the default backend uses on macOS/Linux),
 * runs it, streams its stdout/stderr untouched, and appends ONE result
 * record to stdout: `__KEPCUP_RESULT_V1__<base64url json>__KEPCUP_RESULT_END__\n`
 * carrying `{ exitCode, timedOut, violations }` (the command output itself
 * stays in the streams the host already accumulates). What keeps command
 * output from FORGING that record (BR-P12-005): the parser accepts only the
 * LAST record with both markers, with nothing but whitespace after it and
 * valid JSON inside — so output that merely contains the markers cannot
 * displace the real record — and the request carries a ONE-TIME NONCE the
 * record must echo; the host rejects records whose nonce does not match its
 * request (the nonce travels on the shim's stdin and is never passed into
 * the sandboxed command). A precise statement of the residual risk: a
 * process that could read the shim's own memory could still forge a record —
 * the protocol raises that bar far above "echo marker text", it does not
 * attempt the impossible "unforgeable against the sandbox's own root".
 *
 * Pure functions — unit tests on the host cover encode/parse edge cases;
 * the shim side is exercised by the rootfs self-check (`--selfcheck`) on the
 * target platform (todo/cross-platform-acceptance.md P12).
 */

export interface KepcupExecRequest {
  /** Command line to wrap with srt inside the VM. */
  command: string;
  /** In-distro working directory (already mapped). */
  cwd: string;
  timeoutMs: number;
  /** srt-shaped filesystem config (srtFilesystemFor output, distro paths). */
  filesystem: {
    denyRead: string[];
    allowRead?: string[];
    allowWrite?: string[];
    denyWrite?: string[];
  };
  /** srt-shaped network config (srtNetworkConfigFor output). */
  network: {
    allowedDomains: string[];
    deniedDomains: string[];
    deniedResolvedAddresses: string[];
    strictAllowlist: boolean;
    allowLocalBinding: boolean;
  };
  /** Environment for the wrapped command (already distro-side). */
  env: Record<string, string>;
  /**
   * One-time token generated by the host per exec (BR-P12-005): the result
   * record must echo it and the host rejects mismatches.
   */
  nonce?: string;
}

export interface KepcupExecResponse {
  exitCode: number | null;
  timedOut: boolean;
  violations: SandboxViolation[];
  /** Echo of the request nonce (absent for nonce-less requests). */
  nonce?: string;
}

/** Serializes the request for the shim's stdin. */
export function encodeExecRequest(request: KepcupExecRequest): string {
  return JSON.stringify(request);
}

/** Marker + payload the shim appends after the command output. */
export function encodeExecResponse(response: KepcupExecResponse): string {
  return `${KEPCUP_RESULT_BEGIN}${Buffer.from(JSON.stringify(response), 'utf8').toString('base64url')}${KEPCUP_RESULT_END}`;
}

export class KepcupProtocolError extends Error {}

/**
 * Splits raw shim output into the command's own stdout/stderr and the
 * structured result. Reads from the END of the stream: the last complete
 * `BEGIN…END` record wins, everything before it is command output. A
 * missing/corrupt record throws — callers must treat that as a failed exec,
 * never as "exit 0".
 */
export function parseExecResponse(
  raw: { stdout: Buffer | string; stderr: Buffer | string },
  options: { expectedNonce?: string } = {},
): {
  result: KepcupExecResponse;
  stdout: string;
  stderr: string;
} {
  const stdoutRaw = typeof raw.stdout === 'string' ? Buffer.from(raw.stdout, 'utf8') : raw.stdout;
  const stderrText = typeof raw.stderr === 'string' ? raw.stderr : raw.stderr.toString('utf8');
  const stdoutText = stdoutRaw.toString('utf8');

  const begin = stdoutText.lastIndexOf(KEPCUP_RESULT_BEGIN);
  if (begin < 0) {
    throw new KepcupProtocolError('shim 输出缺少结果记录（KEPCUP_RESULT_BEGIN）');
  }
  const endMarkerAt = stdoutText.indexOf(KEPCUP_RESULT_END, begin + KEPCUP_RESULT_BEGIN.length);
  if (endMarkerAt < 0) {
    throw new KepcupProtocolError('shim 结果记录不完整（KEPCUP_RESULT_END 缺失）');
  }
  // Only accept a TERMINAL record: after the END marker nothing but
  // whitespace may follow, so output that merely CONTAINS the markers cannot
  // forge a result.
  const tail = stdoutText.slice(endMarkerAt + KEPCUP_RESULT_END.length);
  if (tail.trim().length > 0) {
    throw new KepcupProtocolError('shim 结果记录之后仍有输出，拒绝解析');
  }
  const payload = stdoutText.slice(begin + KEPCUP_RESULT_BEGIN.length, endMarkerAt);
  let parsed: unknown;
  try {
    parsed = JSON.parse(Buffer.from(payload, 'base64url').toString('utf8'));
  } catch (error) {
    throw new KepcupProtocolError(`shim 结果记录不是合法 JSON：${error instanceof Error ? error.message : String(error)}`);
  }
  const result = decodeResponse(parsed);
  // BR-P12-005: a record is only trusted together with the nonce of the
  // request that produced it — command output alone cannot fake one.
  if (options.expectedNonce !== undefined && result.nonce !== options.expectedNonce) {
    throw new KepcupProtocolError('shim 结果记录的 nonce 与请求不匹配，拒绝解析');
  }
  return {
    result,
    stdout: stdoutText.slice(0, begin),
    stderr: stderrText,
  };
}

/** Shape-validates the decoded record (fail-closed on unknown shapes). */
function decodeResponse(value: unknown): KepcupExecResponse {
  if (typeof value !== 'object' || value === null) {
    throw new KepcupProtocolError('shim 结果记录形状不正确');
  }
  const record = value as Record<string, unknown>;
  const exitCode = record['exitCode'];
  if (typeof exitCode !== 'number' && exitCode !== null) {
    throw new KepcupProtocolError('shim 结果记录缺少 exitCode');
  }
  const violations = Array.isArray(record['violations'])
    ? (record['violations'] as unknown[])
        .filter((entry): entry is Record<string, unknown> => typeof entry === 'object' && entry !== null && typeof (entry as Record<string, unknown>)['line'] === 'string')
        .map((entry) => ({
          line: entry['line'] as string,
          ...(typeof entry['command'] === 'string' ? { command: entry['command'] as string } : {}),
        }))
    : [];
  const nonce = typeof record['nonce'] === 'string' ? record['nonce'] : undefined;
  return {
    exitCode,
    timedOut: record['timedOut'] === true,
    violations,
    ...(nonce !== undefined ? { nonce } : {}),
  };
}
